id: A88F7DB74
title: 'A Lament of Faith: A Short Remembrance of, and Prayer to, My Guru, the Wish-Fulfilling
  Jewel'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:24:14.812043
  last_modified_at: 2022-03-01 00:24:14.812057
