id: A88F7DB74
title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:24:14.821923
  last_modified_at: 2022-03-01 00:24:14.821929
